# Generated by Django 5.0.2 on 2024-02-28 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('desription', models.TextField(blank=True)),
                ('category', models.CharField(max_length=255)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.URLField()),
                ('video_uploaded_url', models.URLField()),
                ('video_file', models.FileField(upload_to='storage/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('common.commonmodel',),
        ),
    ]
