version: '3.11'
services:
  # First Container : Django
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=youtube
      - DB_USER=samiiz
      - DB_PASS=password123
    depends_on:
      - db

  # Second Container : PostgreSQL
  db:
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=youtube
      - POSTGRES_USER=samiiz
      - POSTGRES_PASSWORD=password123